export const ROUTES = {
    LANDING_SCREEN: 'LANDING_SCREEN',
    REGISTER_SCREEN: 'REGISTER_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    MOVIE_DETAILS_SCREEN: 'MOVIE_DETAILS_SCREEN'
};
